<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Tests.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.Extensions.AI" />
    <PackageReference Include="FSharp.Control.AsyncSeq" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FsVoice.QA\FsVoice.QA.fsproj" />
    <ProjectReference Include="..\FsVoice.Abstractions\FsVoice.Abstractions.fsproj" />
    <ProjectReference Include="..\FsVoice.Core\FsVoice.Core.fsproj" />
    <ProjectReference Include="..\FsVoice.Hosting.AspNetCore\FsVoice.Hosting.AspNetCore.fsproj" />
    <ProjectReference Include="..\FsVoice.Testing\FsVoice.Testing.fsproj" />
    <ProjectReference Include="..\FsVoice.Tools\FsVoice.Tools.fsproj" />
    <ProjectReference Include="..\FsVoice.Types\FsVoice.Types.fsproj" />
    <ProjectReference Include="..\Speak2Docs.Orchestration\Speak2Docs.Orchestration.fsproj" />
  </ItemGroup>

</Project>
