<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="scripts\recorder.fsx" />
    <None Include="scripts\packages.fsx" />
    <None Include="scripts\test_serialization.fsx" />
    <None Include="scripts\testoperator.fsx" />
    <Compile Include="Log.fs" />
    <Compile Include="FsResponses.fs" />
    <Compile Include="WebSocket.fs" />
    <Compile Include="ResponsesTransport.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FSharp.SystemTextJson" />
    <PackageReference Include="FSharp.Control.Websockets.TPL" />
    <PackageReference Include="Microsoft.Extensions.AI" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="FSharp.Core" />
  </ItemGroup>

</Project>
