<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>FsVoice.Cli</RootNamespace>
    <DisableImplicitFSharpCoreReference>true</DisableImplicitFSharpCoreReference>
    <NoWarn>$(NoWarn);57</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FsVoice.Core\FsVoice.Core.fsproj" />
    <ProjectReference Include="..\FsVoice.Ctx.Runtime\FsVoice.Ctx.Runtime.fsproj" />
    <ProjectReference Include="..\FsVoice.Retrieval\FsVoice.Retrieval.fsproj" />
    <ProjectReference Include="..\FsVoice.Retrieval.PdfRasterization\FsVoice.Retrieval.PdfRasterization.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FSharp.SystemTextJson" />
    <PackageReference Include="FSharp.Core" />
    <PackageReference Include="Microsoft.Extensions.AI" />
    <PackageReference Include="Microsoft.Extensions.AI.OpenAI" />
    <PackageReference Include="OpenAI" />
    <PackageReference Include="FsColbert.Models.MxbaiEdgeColbertV0_32M.Onnx.Int8" />
  </ItemGroup>

</Project>
