namespace FsVoiceDemo

module Icons =
    let mic = "\ue029"
    let power = "\ue8ac"
    let play = "\ue037"
    let stop = "\ue047"
    let settings = "\ue8b8"
    let visible = "\ue8f4"
    let visibilityOff = "\ue8f5"
    let preview = "\ue8f4"
    let back = "\ue5c4"
    let refresh = "\ue5d5"
    let uploadFile = "\uf09b"
    let archive = "\ue149"
    let save = "\ue161"
    let add = "\ue145"
    let remove = "\ue15b"
    let clear = "\ue872"
    let delete = "\ue872"
    let deleteForever = "\ue92b"
    let signalDisconnected = "\uf239"
    let signalConnected = "\uf0eb"
